version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/code/static
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db