# Generated by Django 2.2.14 on 2021-06-21 08:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "video_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("video_title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "thumbnails",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                ("channel_id", models.CharField(max_length=100, unique=True)),
                ("channel_title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Youtube Video",
                "verbose_name_plural": "Youtube Videos",
                "db_table": "youtube_video",
            },
        ),
        migrations.CreateModel(
            name="YoutubeVideoCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("api_key", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("deactivated", "deactivated"),
                            ("exhausted", "exhausted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Api Key",
                "verbose_name_plural": "Api Keys",
                "db_table": "api_key",
            },
        ),
    ]
