# Generated by Django 2.2.14 on 2021-06-20 18:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "video_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "thumbnails",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
            ],
            options={
                "verbose_name": "Youtube Video",
                "verbose_name_plural": "Youtube Videos",
                "db_table": "youtube_video",
            },
        ),
    ]
