# Generated by Django 2.2.14 on 2021-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="channel_id",
            field=models.CharField(max_length=100),
        ),
    ]
