# Generated by Django 2.2.14 on 2021-06-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0002_auto_20210621_0847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubevideo",
            options={
                "ordering": ("-published_at",),
                "verbose_name": "Youtube Video",
                "verbose_name_plural": "Youtube Videos",
            },
        ),
    ]
